### ISSUE TITLE
bug: nothing happens when copy button is pressed in the firefox android version

### ISSUE THREAD

**Issue by leynier** [dlcastillop/paylink#20]
I'll try to reproduce it on my phone (because the error happened on a friend's phone) and on the Windows version of Firefox.

**Comment by dlcastillop** [comment]
It seems to be some kind of incompatibility between browsers in this aspect. I tried it with Opera on my phone and happened the same.

Thanks for noticing this. I will solve it soon.

**Comment by dlcastillop** [comment]
Fixed!!!
