### ISSUE TITLE
I think you forgot to include a license (LICENSE.md)

### ISSUE THREAD

**Issue by IngrownMink4** [dlcastillop/paylink#21]
You should add a license to your software to avoid legal problems.

![Captura desde 2022-09-26 18-01-57](https://user-images.githubusercontent.com/25466522/192325366-e4b1a2f5-80be-4e6d-917a-0abd29522312.png)

You have many to choose from [here](https://choosealicense.com/).
I think AGPLv3 or MIT license can fit your software well!

Btw, [I'm Twitter's annoying guy](https://twitter.com/IngrownMink4/status/1574150780801585152). 
I came in to take a look at your work (I really like it, maybe I'll use it in the future <3 cheers).

**Comment by dlcastillop** [comment]
You are right. Thanks for noticing. I will add one and I hope to see your PayLink page soon. 🙌

**Comment by dlcastillop** [comment]
Done!
